# Generated by Django 5.2.9 on 2025-12-09 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('foto', models.ImageField(default='doctores/default.jpg', upload_to='doctores/')),
                ('horario', models.CharField(default='Lun - Vie: 9am - 5pm', max_length=100)),
                ('capacidad_diaria', models.IntegerField(default=10, help_text='Máximo de citas por día')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.doctor')),
            ],
        ),
    ]
