# Generated by Django 5.2.9 on 2025-12-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula/ID'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado/CV'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Sobre mí'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Perfil de LinkedIn'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='capacidad_diaria',
            field=models.IntegerField(default=10),
        ),
    ]
