# Generated by Django 5.2.9 on 2026-03-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='perfil',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('doctor', 'Doctor')], default='paciente', max_length=10),
        ),
    ]
