# Generated by Django 5.2.9 on 2025-12-10 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_doctor_cedula_doctor_certificado_doctor_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='certificado',
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='certificados/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='dashboard.doctor')),
            ],
        ),
    ]
