# Generated by Django 5.2.9 on 2025-12-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_doctor_certificado_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
