# Generated by Django 5.2.7 on 2025-12-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_cita_options_cita_creada_en_alter_cita_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.RemoveField(
            model_name='cita',
            name='creada_en',
        ),
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.doctor'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
