# Generated by Django 5.2.9 on 2025-12-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_cita_options_remove_cita_creada_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
    ]
